---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: bggdb-pvc
  namespace: workshop03
spec:
  accessModes:
    - ReadWriteOncePod
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 1Gi

--- 
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: bggdb-deploy
  namespace: workshop03
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: bgg 
      name: bggdb-po
  template:
    metadata:
      labels:
        app: bgg 
        name: bggdb-po
    spec:
      volumes:
      - name: db-vol 
        persistentVolumeClaim: 
          claimName: bggdb-pvc
      containers:
      - name: bggdb-container
        image: chukmunnlee/bgg-database:nov-2025
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: bgg-secret
        ports:
        - name: db-port 
          containerPort: 3306
        volumeMounts:
        - name: db-vol 
          mountPath: /var/lib/mysql

--- 
apiVersion: v1 
kind: Service
metadata:
  name: bggdb-svc
  namespace: workshop03
spec:
  type: ClusterIP
  selector:
    app: bgg 
    name: bggdb-po
  ports:
  - port: 3306
    targetPort: db-port
