---
apiVersion: v1 
kind: Namespace
metadata:
  name: day03

--- 
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: dov-bear 
  namespace: day03
  labels:
    name: dov-bear
spec:
  replicas: 3
  selector:
    matchLabels:
      name: dov-bear-po
  template:
    metadata: 
      labels:
        name: dov-bear-po
    spec:
      # define volumes
      volumes: 
      - name: configs-vol
        configMap: 
          name: dov-bear-cm
      - name: secrets-vol
        secret:
          secretName: dov-bear-secret
      containers:
      - name: dov-bear-container
        image: chukmunnlee/dov-bear:v1 
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: '5000'
        - name: INSTANCE_HASH
          valueFrom:
            fieldRef:
              # injected from the environment
              fieldPath: status.podIP
        envFrom:
        - secretRef:
            name: dov-bear-secret
        ports:
        - name: web 
          containerPort: 5000
        # mount the volume into the container
        volumeMounts:
        - name: configs-vol
          mountPath: /configs
          readOnly: true
        - name: secrets-vol
          mountPath: /secrets
          readOnly: true

--- 
apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: dov-bear-cm 
  namespace: day03
data:
  my_host: |
    127.0.0.1 localhost
    127.0.1.1 batcomputer

    # The following lines are desirable for IPv6 capable hosts
    ::1     ip6-localhost ip6-loopback
    fe00::0 ip6-localnet
    ff00::0 ip6-mcastprefix
    ff02::1 ip6-allnodes
    ff02::2 ip6-allrouters

  coc-settings.json: |
    {
        "javascript.suggest.autoImports": true,
        "typescript.suggest.autoImports": true,
        "java.inlayHints.parameterNames.enabled": "none",
        "pyright.inlayHints.variableTypes": false,
        "pyright.inlayHints.functionReturnTypes": false,
        "pyright.inlayHints.parameterTypes": false,
        "yaml.schemaStore.enable": true,
      "java.configuration.runtimes": [
        {
          "name": "JavaSE-22",
          "path": "/opt/java/javase/jdk-22.0.2"
        }
      ],
      "java.compile.nullAnalysis.mode": "automatic",
      "godot.enable": true,
      "godot.host": "127.0.0.1",
      "godot.port": 6005
    }
---
apiVersion: v1
kind: Service
metadata:
  name: dov-bear
  namespace: day03
spec:
  # type of service - ClusterIP, NodePort, LoadBalancer
  type: NodePort
  selector:
    name: dov-bear-po
  ports:
  - port: 8080
    targetPort: web
    # caution!
    nodePort: 32000

--- 
apiVersion: v1 
kind: Secret
metadata: 
  name: dov-bear-secret
  namespace: day03
# opaque - user secrets
type: Opaque
data:
  INSTANCE_NAME: ZG92LWJlYXI=