---
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: fortune-deploy 
  namespace: myns
  labels:
    app: fortune 
    env: prod
spec:
  replicas: 5
  selector:
    matchLabels:
      name: fortune 
      env: prod
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 20%
      maxUnavailable: 0%
  template:
    metadata:
      name: my-fortune
      labels: 
        name: fortune 
        env: prod
    spec:
      containers:
      - name: fortune-container
        image: chukmunnlee/myfortune:v1.2
        #image: chukmunnlee/countingbook:v1.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000