---
apiVersion: v1 
kind: Service 
metadata: 
  name: fortune-svc 
  namespace: myns
spec:
  # options: ClusterIP, NodePort
  type: ClusterIP
  selector: 
    name: fortune 
    env: prod
  ports:
  - port: 80 # service port
    targetPort: 3000 # containerPort