---
apiVersion: v1
kind: Namespace
metadata:
  name: workshop02
  labels:
    dept: eng
    env: prod

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counting
  namespace: workshop02
  labels:
    dept: eng
    env: prod
    name: counting
spec:
  replicas: 3
  selector:
    matchLabels:
      name: counting-po
      dept: eng
      env: prod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    # pod template
    metadata:
      labels:
        name: counting-po
        dept: eng
        env: prod
    spec:
      containers:
      - name: counting-container
        image: chukmunnlee/countingbook:v1.1
        imagePullPolicy: IfNotPresent
        ports:
        - name: web
          containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: conting
  namespace: workshop02
  labels:
    dept: eng
    env: prod
spec:
  # type of service - ClusterIP, NodePort, LoadBalancer
  type: NodePort
  selector:
    name: counting-po
    dept: eng
    env: prod
  ports:
  - port: 8080
    targetPort: web
    # caution!
    nodePort: 32000
