---
apiVersion: v1
kind: Service
metadata:
  name: mysql-hsvc
  namespace: day04
spec:
  clusterIP: None
  selector:
    name: mysql
  ports:
  - port: 3306
    targetPort: 3306

--- 
apiVersion: apps/v1 
kind: StatefulSet 
metadata: 
  name: mysql 
  namespace: day04 
spec:
  replicas: 2
  serviceName: mysql-hsvc
  selector: 
    matchLabels:
      name: mysql
  volumeClaimTemplates:
  - metadata: 
      name: data-vol
    spec:
      accessModes: [ ReadWriteOnce ]
      storageClassName: do-block-storage
      resources:
        requests:
          storage: 1Gi
  template:
    metadata:
      labels:
        name: mysql
    spec: 
      volumes:
      - name: data-vol 
        persistentVolumeClaim: 
          claimName: data-pvc
      containers:
      - name: mysql-container 
        image: mysql:8 
        imagePullPolicy: IfNotPresent
        env: 
        - name: MYSQL_ROOT_PASSWORD
          value: adminadmin
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: data-vol 
          mountPath: /var/lib/mysql