---
apiVersion: v1 
kind: Namespace
metadata: 
  name: workshop04

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rustfs-cm
  namespace: workshop04
data:
  RUSTFS_ADDRESS: 0.0.0.0:9000
  RUSTFS_CONSOLE_ADDRESS: 0.0.0.0:9001
  RUSTFS_CONSOLE_ENABLE: "true"
  RUSTFS_VOLUMES: "http://rustfs-sts-{0...2}.rustfs-hsvc.workshop04.svc.cluster.local:9000/data"

--- 
apiVersion: v1
kind: Secret 
metadata:
  name: rustfs-secret 
  namespace: workshop04
type: Opaque
# stringData do not need to base64 value
stringData:
  RUSTFS_ACCESS_KEY: admin
  RUSTFS_SECRET_KEY: adminadmin1234
